version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: destinydatabase
      POSTGRES_USER: destinypro
      POSTGRES_PASSWORD: password